"""Hardcoded Project Gutenberg ebook IDs — verified classics only."""
from __future__ import annotations

GUTENBERG_IDS: dict[tuple[str, str], int] = {
    ("the republic", "plato"): 1497,
    ("nicomachean ethics", "aristotle"): 8438,
    ("the nicomachean ethics", "aristotle"): 8438,
    ("meditations on first philosophy", "descartes"): 59,
    ("critique of pure reason", "kant"): 4280,
    ("thus spoke zarathustra", "nietzsche"): 1998,
    ("beyond good and evil", "nietzsche"): 4363,
    ("the world as will and representation", "schopenhauer"): 38427,
    ("meditations", "marcus aurelius"): 2680,
    ("enchiridion", "epictetus"): 45109,
    ("the enchiridion", "epictetus"): 45109,
    ("essays", "montaigne"): 3600,
    ("tractatus logico-philosophicus", "wittgenstein"): 5740,
    ("tractatus", "wittgenstein"): 5740,
    ("groundwork for the metaphysics of morals", "kant"): 5682,
    ("the symposium", "plato"): 1600,
    ("letter to menoeceus", "epicurus"): 872,
    ("monadology", "leibniz"): 5477,
    ("an essay concerning human understanding", "locke"): 10615,
    ("philosophical investigations", "wittgenstein"): 5827,
    ("the interpretation of dreams", "freud"): 4909,
    ("principles of psychology", "william james"): 49524,
    ("the ego and the id", "freud"): 59830,
    ("conditioned reflexes", "pavlov"): 67627,
    ("the federalist papers", "hamilton madison jay"): 1404,
    ("leviathan", "hobbes"): 1228,
    ("two treatises of government", "locke"): 7370,
    ("the social contract", "rousseau"): 46333,
    ("the prince", "machiavelli"): 1232,
    ("democracy in america", "tocqueville"): 815,
    ("on liberty", "mill"): 34901,
    ("utilitarianism", "mill"): 11224,
    ("introduction to the principles of morals and legislation", "bentham"): 29801,
    ("history of the peloponnesian war", "thucydides"): 7142,
    ("the decline and fall of the roman empire", "gibbon"): 731,
    ("the art of war", "sun tzu"): 132,
    ("the histories", "herodotus"): 17157,
    ("the gallic wars", "caesar"): 10657,
    ("the bible king james version", ""): 10,
    ("tao te ching", "lao tzu"): 216,
    ("dao de jing", "lao tzu"): 216,
    ("bhagavad gita", ""): 2388,
    ("dhammapada", ""): 6602,
    ("the dhammapada", ""): 6602,
    ("the golden bough", "frazer"): 3623,
    ("the analects", "confucius"): 3330,
    ("zhuangzi", "zhuangzi"): 26153,
    ("the butterfly dream", "zhuangzi"): 26153,
    ("the wealth of nations", "adam smith"): 3300,
    ("das kapital", "marx"): 61,
    ("the theory of the leisure class", "veblen"): 3177,
    ("the elements", "euclid"): 21076,
    ("relativity the special and general theory", "einstein"): 5001,
    ("a mathematical theory of communication", "shannon"): 11848,
    ("how to solve it", "polya"): 57737,
    ("on the origin of species", "darwin"): 2009,
    ("experiments on plant hybridization", "mendel"): 4015,
    ("what is life", "schrodinger"): 26357,
    ("principia mathematica", "newton"): 28233,
    ("on the revolutions of celestial spheres", "copernicus"): 20846,
    ("sidereus nuncius", "galileo"): 7785,
    ("harmonices mundi", "kepler"): 33582,
    ("lectures on gas theory", "boltzmann"): 28485,
    ("crime and punishment", "dostoevsky"): 2554,
    ("the brothers karamazov", "dostoevsky"): 28054,
    ("notes from underground", "dostoevsky"): 600,
    ("the death of ivan ilyich", "tolstoy"): 25908,
    ("war and peace", "tolstoy"): 2600,
    ("anna karenina", "tolstoy"): 986,
    ("don quixote", "cervantes"): 996,
    ("faust", "goethe"): 14591,
    ("the divine comedy", "dante"): 8800,
    ("the odyssey", "homer"): 1727,
    ("the iliad", "homer"): 6130,
    ("the aeneid", "virgil"): 228,
    ("the metamorphosis", "kafka"): 5200,
    ("the trial", "kafka"): 7849,
    ("romeo and juliet", "shakespeare"): 1513,
    ("steppenwolf", "hesse"): 35997,
    ("siddhartha", "hesse"): 2500,
    ("demian", "hesse"): 2499,
    ("one thousand and one nights", ""): 128,
    ("i ching", ""): 1269,
    ("mahabharata", ""): 15474,
    ("kalevala", ""): 5186,
    ("epic of gilgamesh", ""): 11000,
    ("enuma elish", ""): 16339,
    ("code of hammurabi", ""): 17150,
    ("popol vuh", ""): 16300,
    ("beowulf", ""): 16328,
    ("anglo-saxon chronicle", ""): 657,
    ("de rerum natura", "lucretius"): 785,
    ("works and days", "hesiod"): 348,
    ("theogony", "hesiod"): 348,
    ("rigveda", ""): 5993,
    ("upanishads", ""): 3283,
    ("the upanishads", ""): 3283,
    ("yoga sutras", "patanjali"): 25268,
    ("letters from a stoic", "seneca"): 3794,
    ("discourses", "epictetus"): 871,
    ("poetics", "aristotle"): 6762,
    ("the birth of tragedy", "nietzsche"): 51356,
    ("critique of judgment", "kant"): 48443,
    ("ten books on architecture", "vitruvius"): 20239,
    ("the expression of emotions in man and animals", "darwin"): 1227,
    ("the division of labour in society", "durkheim"): 37937,
    ("the protestant ethic and the spirit of capitalism", "weber"): 56829,
    ("ancient society", "morgan"): 33111,
    ("the gift", "mauss"): 34109,
    ("the evolution of cooperation", "axelrod"): 57434,
    ("the logic of collective action", "olson"): 33157,
    ("the art of loving", "fromm"): 13437,
    ("escape from freedom", "fromm"): 45524,
    ("letters to a young poet", "rilke"): 16305,
    ("on love", "stendhal"): 402,
    ("time and free will", "bergson"): 5682,
    ("matter and memory", "bergson"): 5682,
    ("the nature of the physical world", "eddington"): 33057,
    ("phenomenology of spirit", "hegel"): 39064,
    ("cybernetics", "wiener"): 23175,
}

GUTENBERG_BY_TITLE: dict[str, int] = {
    "the republic": 1497,
    "leviathan": 1228,
    "the prince": 1232,
    "the art of war": 132,
    "the bible king james version": 10,
    "tao te ching": 216,
    "dao de jing": 216,
    "bhagavad gita": 2388,
    "dhammapada": 6602,
    "epic of gilgamesh": 11000,
    "beowulf": 16328,
    "popol vuh": 16300,
    "the iliad": 6130,
    "the odyssey": 1727,
    "don quixote": 996,
    "war and peace": 2600,
    "crime and punishment": 2554,
    "the brothers karamazov": 28054,
    "the divine comedy": 8800,
    "the federalist papers": 1404,
    "on the origin of species": 2009,
    "the wealth of nations": 3300,
    "thus spoke zarathustra": 1998,
    "beyond good and evil": 4363,
    "enchiridion": 45109,
    "utilitarianism": 11224,
    "on liberty": 34901,
    "democracy in america": 815,
    "the metamorphosis": 5200,
    "the trial": 7849,
    "notes from underground": 600,
    "siddhartha": 2500,
    "faust": 14591,
    "the analects": 3330,
    "rigveda": 5993,
    "upanishads": 3283,
    "mahabharata": 15474,
    "kalevala": 5186,
    "one thousand and one nights": 128,
    "i ching": 1269,
    "enuma elish": 16339,
    "code of hammurabi": 17150,
    "de rerum natura": 785,
    "the golden bough": 3623,
    "relativity the special and general theory": 5001,
    "the elements": 21076,
    "a mathematical theory of communication": 11848,
    "nicomachean ethics": 8438,
    "critique of pure reason": 4280,
    "meditations on first philosophy": 59,
}


def lookup_gutenberg_id(title: str, author: str = "") -> int | None:
    t = title.strip().lower()
    a = author.strip().lower()
    if (t, a) in GUTENBERG_IDS:
        return GUTENBERG_IDS[(t, a)]
    if (t, "") in GUTENBERG_IDS:
        return GUTENBERG_IDS[(t, "")]
    return GUTENBERG_BY_TITLE.get(t)


def count_catalog_entries() -> int:
    return len(set(GUTENBERG_IDS.values()) | set(GUTENBERG_BY_TITLE.values()))
