export const SUBJECTS = [
  {
    id: "cosmology",
    title: "SUBJECT_01 // COSMOLOGY",
    tracks: "COSMOLOGY,SCIENCE",
    type: "video" as const,
  },
  {
    id: "ai",
    title: "SUBJECT_02 // ARTIFICIAL INTELLIGENCE",
    tracks: "ARTIFICIAL_INTELLIGENCE",
    type: "video" as const,
    videoSrc: "/videos/subject02_ai.mp4",
  },
  {
    id: "blockchain",
    title: "SUBJECT_03 // BLOCKCHAIN",
    tracks: "BLOCKCHAIN",
    type: "video" as const,
    videoSrc: "/videos/subject03_blockchain.mp4",
  },
  {
    id: "philosophy",
    title: "SUBJECT_04 // PHILOSOPHY",
    tracks: "PHILOSOPHY",
    type: "video" as const,
    videoSrc: "/videos/subject04_philosophy.mp4",
  },
  {
    id: "literature",
    title: "SUBJECT_05 // LITERATURE",
    tracks: "LITERATURE",
    type: "video" as const,
    videoSrc: "/videos/subject05_literature.mp4",
  },
  {
    id: "security",
    title: "SUBJECT_06 // SECURITY",
    tracks: "SECURITY",
    type: "video" as const,
    videoSrc: "/videos/subject06_security.mp4",
  },
  {
    id: "psychology",
    title: "SUBJECT_07 // PSYCHOLOGY",
    tracks: "PSYCHOLOGY",
    type: "video" as const,
    videoSrc: "/videos/subject07_psychology.mp4",
  },
  {
    id: "economics",
    title: "SUBJECT_08 // ECONOMICS",
    tracks: "ECONOMICS",
    type: "video" as const,
    videoSrc: "/videos/subject08_economics.mp4",
  },
  {
    id: "history",
    title: "SUBJECT_09 // HISTORY",
    tracks: "HISTORY",
    type: "video" as const,
    videoSrc: "/videos/subject09_history.mp4",
  },
  {
    id: "politics",
    title: "SUBJECT_10 // POLITICS",
    tracks: "POLITICS",
    type: "video" as const,
    videoSrc: "/videos/subject10_politics.mp4",
  },
  {
    id: "linguistics",
    title: "SUBJECT_11 // LINGUISTICS",
    tracks: "LINGUISTICS",
    type: "video" as const,
    videoSrc: "/videos/subject11_linguistics.mp4",
  },
  {
    id: "zion_research",
    title: "SUBJECT_12 // CIVILIZATION RESEARCH",
    tracks: "ZION_RESEARCH",
    type: "video" as const,
    videoSrc: "/videos/subject12_zionresearch.mp4",
  },
] as const;

export type SubjectConfig = (typeof SUBJECTS)[number];
